### PR TITLE
Support for selecting specific columns

### PR DESCRIPTION
**Pull request by mushketyk**

### CODE REVIEW

**Comment by lbradstreet** [comment]
Looks good. Happy to merge it once the feature is documented in the README (as an optional task-map entry option).

Thanks!

**Comment by mushketyk** [comment]
@lbradstreet Thank you for review. I'll update the README today.

**Comment by mushketyk** [comment]
I've updated README.md file.

**Comment by lbradstreet** [comment]
Thanks! Merged.

**Pull request merged**
