### PR TITLE
support update

### PR DESCRIPTION
**Pull request by tongqqiu**
- zero impact on existing insert write
- add extra :sql/update boolean to indicate if it is update
- :where cause as a map
- see more details on the test case output-update-test

### CODE REVIEW

**Comment by MichaelDrogalis** [comment]
@tongqqiu Thanks for this patch! I'd like to avoid modifications to the `:sql/write` function, as we'd get a performance hit adding a conditional inside a critical path. Can you please create a new `:sql/update` function, mirroring what is currently in `:sql/write`?

**Comment by tongqqiu** [comment]
I don't quite know how to do that separately. So I can define `update-rows-calls` like this

```
(def update-rows-calls
  {:lifecycle/before-task-start inject-update-rows
   :lifecycle/after-task-stop close-update-rows})
```
Then define update-rows like read-rows. Does it mean its type is function not medium? 
```
(defn update-rows
  [pool {:keys [rows where] :as segment}]
  (jdbc/with-db-transaction
    [conn pool]
    (doseq [row rows]
      (jdbc/update! conn (:sql/table task-map) row (sql-dsl/where where)))))
```
Also how to pass `pool` `conn`? My understanding is that there only know `segment` not `event` which contains `task-map`.

**Comment by MichaelDrogalis** [comment]
You'd want to create a parallel set of `defmethod`s for `:sql/update` by comparison to `:sql/write`. Does that make sense? Same approach - just not mixing one with the other.

**Comment by tongqqiu** [comment]
Much simpler than I thought. Done

**Comment by MichaelDrogalis** [comment]
Great, thanks!

**Comment by MichaelDrogalis** [comment]
I applied the patch directly to master using the command line. You can see your commit here: f887264b2a6adee7bc9910639a5d1766e8cd80a0, so I will close this pull request. This has been released on Clojars as `0.6.1-SNAPSHOT`. Thanks!

**Pull request closed without merging**
